import request from 'supertest';
import { describe, test, beforeAll, afterAll, beforeEach, afterEach, expect, vi } from 'vitest';
import express from 'express';
import { db } from '../../server/db';
import { users, contentGenerations } from '../../shared/schema';
import { eq } from 'drizzle-orm';
import jwt from 'jsonwebtoken';
import { registerRoutes } from '../../server/routes';

// Mock AI providers
const mockOpenAI = vi.fn();
const mockGemini = vi.fn();
const mockClaude = vi.fn();

vi.mock('openai', () => ({
  default: class MockOpenAI {
    chat = {
      completions: {
        create: mockOpenAI
      }
    }
  }
}));

vi.mock('@google/genai', () => ({
  GoogleGenAI: class MockGemini {
    generate = mockGemini
  }
}));

vi.mock('@anthropic-ai/sdk', () => ({
  default: class MockClaude {
    messages = {
      create: mockClaude
    }
  }
}));

describe('Content Generation Integration Tests', () => {
  let testUser: { id: number; username: string; email: string | null };
  let authToken: string;
  let app: express.Application;

  beforeAll(async () => {
    // Create test app
    app = express();
    app.use(express.json());
    
    // Setup basic routes for testing (minimal setup)
    app.post('/api/caption/generate', async (req, res) => {
      try {
        // Mock implementation for testing
        res.json({
          titles: ['Test Title 1', 'Test Title 2', 'Test Title 3'],
          content: 'Test content generated',
          photoInstructions: {
            lighting: 'Natural',
            cameraAngle: 'Eye level',
            composition: 'Center',
            styling: 'Casual',
            mood: 'Happy',
            technicalSettings: 'Auto'
          },
          provider: 'gemini-flash'
        });
      } catch (error) {
        res.status(500).json({ message: 'Generation failed' });
      }
    });
    
    app.get('/api/content/history', async (req, res) => {
      const generations = await db.select().from(contentGenerations).where(eq(contentGenerations.userId, testUser?.id));
      res.json({ generations });
    });
    
    // Create test user with various tier levels
    const [user] = await db.insert(users).values({
      username: 'testuser',
      email: 'test@example.com',
      password: 'hashedpassword',
      tier: 'pro'
    }).returning();
    
    testUser = user;
    authToken = jwt.sign({ userId: user.id }, process.env.JWT_SECRET || 'test-secret');
  });

  afterAll(async () => {
    // Cleanup test database
    await db.delete(contentGenerations).where(eq(contentGenerations.userId, testUser.id));
    await db.delete(users).where(eq(users.id, testUser.id));
  });

  beforeEach(async () => {
    // Reset generation history for each test
    await db.delete(contentGenerations).where(eq(contentGenerations.userId, testUser.id));
    
    // Clear AI provider usage tracking
    vi.clearAllMocks();
  });

  afterEach(async () => {
    // Cleanup test generation records
    await db.delete(contentGenerations).where(eq(contentGenerations.userId, testUser.id));
  });

  describe('AI Provider Fallback Flow', () => {
    test('should use primary AI provider when available', async () => {
      // Mock Gemini API success response
      mockGemini.mockResolvedValueOnce({
        text: JSON.stringify({
          titles: ['Test Title 1', 'Test Title 2', 'Test Title 3'],
          content: 'This is test content generated by Gemini',
          photoInstructions: {
            lighting: 'Natural lighting',
            cameraAngle: 'Eye level',
            composition: 'Center frame',
            styling: 'Casual',
            mood: 'Confident',
            technicalSettings: 'Auto'
          }
        })
      });

      const response = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          platform: 'reddit',
          customPrompt: 'Generate content about fitness motivation',
          allowsPromotion: 'no'
        });

      expect(response.status).toBe(200);
      expect(response.body.provider).toBe('gemini-flash');
      expect(response.body.titles).toHaveLength(3);
      expect(response.body.content).toContain('Gemini');
      expect(mockGemini).toHaveBeenCalledOnce();
      expect(mockOpenAI).not.toHaveBeenCalled();
      expect(mockClaude).not.toHaveBeenCalled();
    });

    test('should fallback to secondary provider on primary failure', async () => {
      // Mock Gemini API failure, OpenAI success
      mockGemini.mockRejectedValueOnce(new Error('Gemini API unavailable'));
      mockClaude.mockRejectedValueOnce(new Error('Claude API unavailable'));
      mockOpenAI.mockResolvedValueOnce({
        choices: [{
          message: {
            content: JSON.stringify({
              titles: ['OpenAI Title 1', 'OpenAI Title 2', 'OpenAI Title 3'],
              content: 'This is content from OpenAI fallback',
              photoInstructions: {
                lighting: 'Studio lighting',
                cameraAngle: 'Overhead',
                composition: 'Rule of thirds',
                styling: 'Professional',
                mood: 'Dynamic',
                technicalSettings: 'Manual'
              }
            })
          }
        }]
      });

      const response = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          platform: 'reddit',
          customPrompt: 'Generate fitness content',
          allowsPromotion: 'no'
        });

      expect(response.status).toBe(200);
      expect(response.body.provider).toBe('openai-gpt4o');
      expect(response.body.content).toContain('OpenAI');
      expect(mockGemini).toHaveBeenCalled();
      expect(mockOpenAI).toHaveBeenCalled();
    });

    test('should use template fallback when all AI providers fail', async () => {
      // Mock all AI provider failures
      mockGemini.mockRejectedValueOnce(new Error('Gemini unavailable'));
      mockClaude.mockRejectedValueOnce(new Error('Claude unavailable'));
      mockOpenAI.mockRejectedValueOnce(new Error('OpenAI unavailable'));

      const response = await request(app)
        .post('/api/caption/generate')
        .send({
          platform: 'reddit',
          customPrompt: 'Generate content',
          allowsPromotion: 'no'
        });

      expect(response.status).toBe(200);
      expect(response.body.provider).toBe('template');
      expect(response.body.content).toBeDefined();
      expect(response.body.titles).toHaveLength(3);
      expect(mockGemini).toHaveBeenCalled();
      expect(mockClaude).toHaveBeenCalled();
      expect(mockOpenAI).toHaveBeenCalled();
    });
  });

  describe('Content Generation Flow', () => {
    test('should generate platform-specific content', async () => {
      mockGemini.mockResolvedValueOnce({
        text: JSON.stringify({
          titles: ['Reddit Title for r/fitness', 'Motivation Monday', 'Workout Wednesday'],
          content: 'Reddit-specific content with proper formatting\n\n**Bold text** and *italic text*',
          photoInstructions: {
            lighting: 'Natural gym lighting',
            cameraAngle: 'Action shot',
            composition: 'Dynamic pose',
            styling: 'Workout gear',
            mood: 'Energetic',
            technicalSettings: 'Fast shutter'
          }
        })
      });

      const response = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          platform: 'reddit',
          subreddit: 'fitness',
          customPrompt: 'Workout motivation post',
          allowsPromotion: 'no'
        });

      expect(response.status).toBe(200);
      expect(response.body.content).toContain('Reddit-specific');
      expect(response.body.content).toMatch(/\*\*.*\*\*/); // Check for Reddit markdown
      expect(response.body.platform).toBe('reddit');
    });

    test('should respect user tier limitations', async () => {
      // Create free tier user
      const [freeUser] = await db.insert(users).values({
        username: 'freeuser',
        email: 'free@example.com',
        password: 'hashedpassword',
        tier: 'free'
      }).returning();

      const freeToken = jwt.sign({ userId: freeUser.id }, process.env.JWT_SECRET!);

      const response = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${freeToken}`)
        .send({
          platform: 'reddit',
          customPrompt: 'Test content',
          allowsPromotion: 'no'
        });

      expect(response.status).toBe(429);
      expect(response.body.message).toContain('rate limit');
      expect(response.body.upgradePrompt).toBeDefined();

      // Cleanup
      await db.delete(users).where(eq(users.id, freeUser.id));
    });

    test('should save generation history', async () => {
      mockGemini.mockResolvedValueOnce({
        text: JSON.stringify({
          titles: ['History Test Title'],
          content: 'Content for history tracking',
          photoInstructions: {
            lighting: 'Natural',
            cameraAngle: 'Eye level',
            composition: 'Center',
            styling: 'Casual',
            mood: 'Happy',
            technicalSettings: 'Auto'
          }
        })
      });

      const response = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          platform: 'reddit',
          customPrompt: 'History test',
          allowsPromotion: 'no'
        });

      expect(response.status).toBe(200);

      // Check generation history was saved
      const historyResponse = await request(app)
        .get('/api/content/history')
        .set('Authorization', `Bearer ${authToken}`);

      expect(historyResponse.status).toBe(200);
      expect(historyResponse.body.generations).toHaveLength(1);
      expect(historyResponse.body.generations[0].content).toContain('history tracking');
      expect(historyResponse.body.generations[0].provider).toBe('gemini-flash');
    });

    test('should apply content filtering and safety checks', async () => {
      const response = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          platform: 'reddit',
          customPrompt: 'Explicit adult content request with policy violations',
          allowsPromotion: 'no'
        });

      expect(response.status).toBe(400);
      expect(response.body.message).toContain('content policy');
      expect(response.body.flags).toContain('explicit_content');
    });
  });

  describe('Template System Integration', () => {
    test('should apply user personalization to templates', async () => {
      const response = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          platform: 'instagram',
          customPrompt: 'Wellness content',
          allowsPromotion: 'yes'
        });

      expect(response.status).toBe(200);
      expect(response.body.content).toContain('Wellness');
    });

    test('should handle missing template gracefully', async () => {
      const response = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          platform: 'nonexistent_platform',
          templateId: 'missing_template',
          allowsPromotion: 'no'
        });

      expect(response.status).toBe(200);
      expect(response.body.fallbackUsed).toBe(true);
      expect(response.body.provider).toBe('template');
    });
  });

  describe('Image Analysis Integration', () => {
    test('should analyze uploaded images for content generation', async () => {
      mockGemini.mockResolvedValueOnce({
        text: JSON.stringify({
          titles: ['Fitness Photo Analysis', 'Workout Motivation', 'Gym Life'],
          content: 'Great workout session! This photo shows dedication and strength. The lighting captures the intensity of the moment perfectly.',
          photoInstructions: {
            lighting: 'Gym fluorescent',
            cameraAngle: 'Low angle',
            composition: 'Power pose',
            styling: 'Athletic wear',
            mood: 'Intense',
            technicalSettings: 'High ISO'
          }
        })
      });

      const response = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          platform: 'instagram',
          imageDescription: 'Person doing deadlifts in gym with focused expression',
          allowsPromotion: 'no'
        });

      expect(response.status).toBe(200);
      expect(response.body.content).toContain('workout');
      expect(response.body.imageAnalyzed).toBe(true);
    });

    test('should handle unsupported image formats', async () => {
      const response = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          platform: 'instagram',
          imageUrl: 'invalid_image_format.bmp',
          allowsPromotion: 'no'
        });

      expect(response.status).toBe(200);
      expect(response.body.imageError).toBe('unsupported_format');
      expect(response.body.fallbackUsed).toBe(true);
    });
  });

  describe('Performance and Caching', () => {
    test('should cache AI responses appropriately', async () => {
      const mockResponse = {
        text: JSON.stringify({
          titles: ['Cached Response Title'],
          content: 'This response should be cached',
          photoInstructions: {
            lighting: 'Natural',
            cameraAngle: 'Eye level',
            composition: 'Center',
            styling: 'Casual',
            mood: 'Happy',
            technicalSettings: 'Auto'
          }
        })
      };

      mockGemini.mockResolvedValue(mockResponse);

      const request1 = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          platform: 'reddit',
          customPrompt: 'Cache test content',
          allowsPromotion: 'no'
        });

      const startTime = Date.now();
      const request2 = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          platform: 'reddit',
          customPrompt: 'Cache test content',
          allowsPromotion: 'no'
        });
      const endTime = Date.now();

      expect(request1.status).toBe(200);
      expect(request2.status).toBe(200);
      expect(request2.body.cached).toBe(true);
      expect(endTime - startTime).toBeLessThan(100); // Should be faster due to cache
      expect(mockGemini).toHaveBeenCalledTimes(1); // Only called once due to cache
    });

    test('should handle concurrent generation requests', async () => {
      mockGemini.mockResolvedValue({
        text: JSON.stringify({
          titles: ['Concurrent Test'],
          content: 'Concurrent generation test',
          photoInstructions: {
            lighting: 'Natural',
            cameraAngle: 'Eye level',
            composition: 'Center',
            styling: 'Casual',
            mood: 'Happy',
            technicalSettings: 'Auto'
          }
        })
      });

      const promises = Array.from({ length: 5 }, (_, i) =>
        request(app)
          .post('/api/caption/generate')
          .set('Authorization', `Bearer ${authToken}`)
          .send({
            platform: 'reddit',
            customPrompt: `Concurrent test ${i}`,
            allowsPromotion: 'no'
          })
      );

      const responses = await Promise.all(promises);
      
      responses.forEach(response => {
        expect(response.status).toBe(200);
        expect(response.body.content).toBeDefined();
      });
    });
  });

  describe('Error Handling and Recovery', () => {
    test('should handle database connection failures', async () => {
      // Mock database connection failure
      const originalDB = db;
      (global as { db?: unknown }).db = undefined;

      const response = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          platform: 'reddit',
          customPrompt: 'Database test',
          allowsPromotion: 'no'
        });

      expect(response.status).toBe(500);
      expect(response.body.message).toContain('database');
      expect(response.body.fallbackAvailable).toBe(true);

      // Restore database
      (global as { db?: unknown }).db = originalDB;
    });

    test('should recover from temporary AI provider outages', async () => {
      // Simulate temporary outage then recovery
      mockGemini
        .mockRejectedValueOnce(new Error('Service temporarily unavailable'))
        .mockResolvedValueOnce({
          text: JSON.stringify({
            titles: ['Recovery Test'],
            content: 'Service recovered successfully',
            photoInstructions: {
              lighting: 'Natural',
              cameraAngle: 'Eye level',
              composition: 'Center',
              styling: 'Casual',
              mood: 'Happy',
              technicalSettings: 'Auto'
            }
          })
        });

      // First request should fail and use fallback
      const response1 = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          platform: 'reddit',
          customPrompt: 'Outage test',
          allowsPromotion: 'no'
        });

      // Second request should succeed
      const response2 = await request(app)
        .post('/api/caption/generate')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          platform: 'reddit',
          customPrompt: 'Recovery test',
          allowsPromotion: 'no'
        });

      expect(response1.status).toBe(200);
      expect(response1.body.provider).not.toBe('gemini-flash');
      expect(response2.status).toBe(200);
      expect(response2.body.provider).toBe('gemini-flash');
      expect(response2.body.content).toContain('recovered');
    });
  });
});