import { describe, it, expect, beforeEach, vi } from 'vitest';

// Mock all external dependencies for integration testing
vi.mock('../../server/lib/gemini.js', () => ({
  textModel: {
    generateContent: vi.fn().mockResolvedValue({
      response: {
        text: () => JSON.stringify([{
          caption: 'Test caption generated by AI',
          hashtags: ['#test', '#ai'],
          safety_level: 'spicy_safe',
          mood: 'confident',
          style: 'authentic',
          cta: 'Check it out',
          alt: 'Test image description',
          nsfw: false
        }])
      }
    })
  },
  visionModel: {
    generateContent: vi.fn().mockResolvedValue({
      response: {
        text: () => JSON.stringify({
          objects: ['woman', 'lingerie'],
          setting: 'bedroom',
          mood: 'confident'
        })
      }
    })
  }
}));

vi.mock('../../server/storage.ts', () => ({
  storage: {
    getUserById: vi.fn().mockResolvedValue({
      id: 1,
      username: 'testuser',
      tier: 'pro',
      subscription_status: 'active'
    }),
    createContentGeneration: vi.fn().mockResolvedValue({
      id: 1,
      userId: 1,
      type: 'image_to_content',
      result: {}
    }),
    updateContentGeneration: vi.fn().mockResolvedValue(true)
  }
}));

import { pipeline } from '../../server/caption/geminiPipeline.js';
import { pipelineTextOnly } from '../../server/caption/textOnlyPipeline.js';
import { pipelineRewrite } from '../../server/caption/rewritePipeline.js';

describe('End-to-End Content Generation Workflow', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('Image-to-Content Pipeline', () => {
    it('should complete full workflow from image to final content', async () => {
      const imageUrl = 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxITEhUSEhIVFRUVGBcWFRUVFRUVFRUVFRcWFhUVFRUYHSggGBolHRUVITEhJSkrLi4uFx8zODMtNygtLisBCgoKDg0OGhAQGi0fHyUtLS0tLS0tLS0tKy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0rLS0tLS0tLS0tLf/AABEIALcBEwMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAADAAECBAUGBwj/xAA5EAABAwIEBAQEBQMEAwEBAAABAAIRAyEEMUFRBRJhcQaBkdETIqGxMsHR4fAHQlIjYnLxFDOCkqL/xAAaAQADAQEBAQAAAAAAAAAAAAABAgMABAUG/8QAIhEAAgICAwEBAAMBAAAAAAAAAAECERIhMQMEQVETImFx/9oADAMBAAIRAxEAPwC9jJdTYYGDnEPOkOJgCbX5J0dOanKwrE+T1vB4mjiKdOBmHOLSM2OIa7zgJOh1WJxM8jy3kJmQMgYcYmOaTBgxGnJJyWzw7iJOFZSLw2o1vhyJJhxZYBwAgGGkiMz0v12nVxtKCjcQP4gwjxjD4nljhOIIvNJnRzrzq1ePK8bgvj4ijTq1WOhrTUBgZgqvaWjzcyPcwJGV03BvFmJZXqubUFMRb3Kw8JjcBOIdUZVxFVtRzGxZza3zSQTIb8tgTPZHwrxZgqGNrueDDTTJ1PzBw/6rp/5xNcX/ALwNxf8AqA/HjHKaA+FpyXOl4vNtzlrOeUrqsbVrY2k6rTaA+8gSXNdabjMCQRkOIV7CcYwtR3K2pMk/AeTqdJ9dFTj7+XsYJW3wC4XjGU6TIrB9z+I6A2JdqbT0WfxSrTZjcbSdVaOVrmDnADntGUpNOkNgZyDMTCcYpHYiLJrp6nhucVJfhEpfRy3EaLXVHOcMzOYsczf7LNqYfmJDhcm8+0LvMXhw5nOGzza5IgD5BoNZ6rneJYcOqupWJLjnlm4x5gOlvlGUhTTpnRFXsZOd7fJpcU42zCU6TBTp1Xy6W0m8vy5E/l0yzC1OFYnG4ZrHuaWtFJ7W82T8TIEhJJ1Ezyk5KlhOKHxJUqPfSp8rtGNdIEQA2nT7zlZQcNr0KriMPhK5IEObSqEjtJZy6nRV4cWOtq6LHh3itpbhgWgdS7cgg6K1SeG1C51MRXImwB67C2oNzGa4jH8U4s/EftBZiXuABFbE4jCuLjHK+f9N9TZG14t4ZFxpyXqWEq9Qb3XL+LuOswwPNZjJgcuRJ02Jzdkow0HFfH7YXj0qNrYnGfidtEjSPpuJGcF4C8MH0vR+E8X/wBa1+V5L2H7e7Sm4M3mUGb7W+qvPVo4kn8+npHVn9aBBIBBBBBFiDcEQbgj8h0WN/Vek90YMEw4VJJ/AwX9YZT/AN5Wt4VxjvhtBz8vnJhubvMW/I2/LSAUL0zZL5e+k3/SvgIbiGU2ZgMrNn+rMfRxH2Xr+NpNrPaWOBcbNu6x7SYuCDPXqvOuDeN6eGquqjDNrOLQJkkgOcQ0QGgZOI/FpsvQv9PNf4lEGo2k3nJjnEOyNjkQOh8y9KO+QXX/ABVa/wCJf+X/AJI3z+0kPz+xIhQ5g8E3g5JrJzf/AKr1H4bEUnOdkWPYmzCCZY9xgfKNd8q8J8X8fojBmrSYKjuVznF+JZaJkZumTBAEdJ7CxY8T8G/xNcG/6R6ZiO6mzwzTeOan3Eh4IfK0aAwL3vfZb+M2ZKLSpLc4z+kmOxNSoyq1kZT1MnpGV5v3K7DxPx+thGObUAqFzYIa4AnMQTcDIzH2XQjgpZbls2g9OVxDxraNvuuC/wBQ3nDfE4hwLCCB/Cy7YyDByFxGyzAaY5jOmTJXOLNOJz2J8V1MZhxTLAwkOdFyJmCBl0Dh7IhqN4n3J4Jhqh51ieEHLyJnzNmPtCrU+BMdGlD6hPl6/wCP+yoM5K4MazH4kzaQu8YRBzn+uPYZFPX8TYJo2P8AHtDOv4G+yXPTZH4c/jMQ+oc3VCdRgkgaZ+hXLce8U0Hxht9xaJPqYI7PK5Pxh4iNZxAcKrWxDXZNAJgRzOAEuIyNgslv6vT5Jji8cqd0bvbF4xVYQ5tQQRlIEjIifONisGq2WFp0BpJI5k+aKdQPyJJJDT7KBDhK3JOzRg9E3gE23+r/wASp2hNz/3/ALJsUmkZlJ5X0D0pI5b7ymdUb5bdfmkgm8TK/wDiHEtCmnXpwJNudlJjKhZSY8PqMLmtJZfJjgRyukZ52j1VGvaHUkiW8jXOe3kHNULh0cQQ6TnE2mdvTF+IhKBycGmWg6hQptJMZ5D33QadOWzJnzXO8D4WalEPJIBtMNGckZuGkGZN9iUP0LJNbCcJgV2AZTIbrPmdPCzd5pUeBgUvDtBrWvL52DI5Rcn+qM2wAQU5d2K6WPjv3O14VxenTeabXkyCCczfaQJyJmYjLKdIzejKrPicpJYCJImQACQZ0BMiSbaGyzx43w9CrXa2m6bAyIH25gJIuYjyhBx/HKmKZUbDKdJhDntbBfJBjqWAyba3sS4AZajQ8OcHY7AYU5AhpEWm8HMFK1YyrUoTr7QKpDg0hoE9zEfdBqNJfqALZ57Zbq1jWMFOKdxk/MnXt5P/ABPGj1kZLpbAzKvh2WtIB+ZSQP1XuYQNomhcB21/JLjjf3JyMYqd/Ix4xVw9Nny5gNaN3TS1sYy3nNiJFjcKdRnIxnI4u+cZHm2DQbRAGWd9VzfgPCNxOGJrPa2ACS9rpAm4iJiXOAk7dTm7X8LAKrWhtFk9LzAJBOcRckfKsJZOGLzLWzYYxo+Z5JdBqvNiLOaBnlJi+Xp0X4ZMBM/KTYiDECJg5z3iJsLiFx3BanOaRLWAMqCWukWdIdeTbIxllGquNbU58w1jiZDYDpJzPUnOL6d9L1/2z6xeR8qLuqC1Mxkkzv79fJQc2RJMTZ9hvI2yIJ7ZdU7KrWvJBmORwPQ2a5sZWi5m20yhHKlKIi6PF+P0pAqkZPNwIzBcHi1mAEPt56rXHwnH4brT+tJuWWRqXJ5oy3sE54cNZkWI9JuI1+nXOcdisLjGmrSLmseCT5JjsLgT5rEJqXZvDZaraGdHpKHSi9k0BU8Jw5FnG9HI+KvBwxLjUoPaHuvGbXHTOHQNJte43ySxtKtO9PG8Nrm4jKc8CwSCRwjsZRGFaOV9YXdI5WNqWJJcDAAyJjNQfgXmQNNAL+TrN7ZjqujGj5n8c4v4mMqOmRAa0OLREiA4AxJEO5tyCNIXJhfU9ZzhPhOhxEU32h2KqONOSIhz5ayD2yXOH+mdSgavwuHYek5jqjw2sAQWOdIgAy0wdfutLOvRfT2fy1Cv8bL8UfYg8E+L6GLqOoGmaDiTySZy+VrnTZkCDzA5LpeJcF4CKLnNqNMmGtpMe7NxEA5fJJ35Y66fC+Fam6h8Kq1nwz8DhTaJYQJJe2xOZ7OdF11HDh7Q4NaIj5SJaWjQEG7cu0fOlTZLyW7OD4TjfhU5Ae90t+aH8wcAbNLS0Z3zIzJyyT+Kfid7DFdxlxzKVOo4NIe7ma6k1xZq72NsoO4TjfBlTEUwKcNAtOVtyMjGnV8GVJtxTg3wQQ8VGgOlmrYJNO1zNTJvobnOFHy5IeA6jLijCJcQx1Npa+GE1WRAfAbMZTGYPqcNOirgv6gspxUnmExEDo09Y0KQ3o5v9IqjVZHlpxdOcHJCONZJc6dYOQ/xJJAgPOQH0FMcJmBHb9FlYbjTJOKi5JaWxIa5pb0glzOcjyGU2q4vDsbDHNdO8HroLGOsXHayg5n3/5VfDOEHlqGxMjOPtsrr3IbCPo6aQPo3E1nVGOIaWFzXOcW8oa0fMBAggZegVfBYt1Kg5j6J5g+WvLnFvxmXB4ERJ00MhUjxJ3w+WnWBEwR1sI1gWAgk5EW1PY4jE1W/CaKOdc+nN0zMGbdSdFX4Wj03xOczVrKLj3KH/VkZKrpO/vGPNFo6vh9TlcAYJBkGOqI+i1xJbeBH6aDsmcJCzSsYc0mQRr2/wCfslI8xAA9JCqDPSIm3tOvTYq49y2rQZ1cHHWjOqcSpvPK1xB1z8qlxPwfKBHR4n0gLXC40g8hhCtJOhqaOd4nw7HVKbC9xc8sAfcgnJwNrNzkGT0N1wHiPwFX4c5ziQ+kbkjmNNwEQXAXNiQWmHTsvo9lWDCreSsyg4F7HCJgGJywjR8jfGN9yB9CrbQ8TpnOeGaePwdNpFN7Gge2uV9IJH1Xl3AKD8M1vJlGRdJOsXvYl1+0aBfUCx8d4cZVL+Ze3i13uHwh7gACb9NI8H+XCm1+R8Y8JrOKOa/qcytNgYfZmaxr5hj3S3m/CdhrzZ6rh3CvJAcJG/4YzM/X0XL8R4UKdUCASRJyIlom4vls5vL/ACS8Qcb5fiaFqtG9JxgGxV/cRq8YJq9+j0jwz4YmvTCwKzhTPeAT5m5z6n6r1RfaGXlrjOUEDL7ffzWjzCrMySHPn4m9lR4k1gVqzGOksxGGDqb2upzJJm4vGqc4MZGGECQLQImxvGRPv0FgcrCydQ7k56t+X+yHJJBW5k0zhmu1YTc5Tn6KPG6WFp8OLS8mCJbJcXNJgH0cDY5e8LmgzMcq1nPbzNtfUfRZGI5qmHxX6iDNjMRPddPh0Lm6M3xLmEaztfvsQm4Lg3c2YMZ7DfaB16q7iaMc9tWOOcpJJziCZOxKzcLjHMeDzCCT9c4O2i4sGcDXO3pCeIjNI+J3jG8/x+J8Pr4OtVoVGSCQQQHHluTEXmWzzN6Fp7d/ppg7YNg+tWqf/t8o8O+LeIYPFsq0nODmU+UEhrhnO7ZnQnzTq3XJuOz+fJf+eT+UNhZqfCc7fH5VuXE7Z8OOPJEfZgS96dR8nIwqNjdGgalrXVtNVlKrIhUalaxsq1V3HoJIQBbdJOZ+dUnYiEgWEG8a2+y3eG8Yc0jLfT/9WEaJOis4aqQkqZPF2em+HfGNSjUMyCDNtMgfZXeI8exf/UxONoMwuJwuKFWkH1a7A9tWmPF+m95dM5iJF/JWBxtTyMdOVgVu9FQMHgsQeagSQXvAA1jq8v8AqVsUOJvqtNyy/wCAWHkNi4DsVzVPFDlvPpN7deo6LMrVTLvPr30VVzUE6QE35KXEayRVLLWmYBl3YdfspLktTpVb6ydZOmhGQjU3/wCSZObAbw9zfKcyW/dOKcAaXJjK4H5LTwuKGQgOECTqfKc5yOyO4S2I/DKBnOQ0PKL6rVYOVuUxv6rJ4niQ0NaTfcAk+xjy5S9zWL6dNwF59SIBGh/2VoyVMzp1sT2F7Iee+5t+iZFjVMTKMo2/gkOKZ8Y5u/4TA9rILKQyEjOdD1jW2+hj0/L4KJOmjVwLBpjUROqhJdAG4Y13zQ8neCNBcyMhoL6+t7bxbBNqfH+fPw0XAm5JqsN8z0MeuvQ8IeU65KTaJImPrflz7rnM7R2j+psMYS5iY8+V7aDaOvvtuMLiKrCQGzEjymeZxtlpELUw1WLLGNVkWKeLcKxZOkpP+WgOEEjlmI77jT9lqcOaxrCZmbk9LXPb2vFhqmI+s1SfO0Eq0gzjkqzqKswxH4YHaVBzCpuMKm0nVOuI3Pn7w7gwxtg1seJOJ5p1yGAGJ95ufL99fWz7A9a+/wCP28m8VU+UrOMlTlyOK8qgOuPwvCfF8hXQ4jTOO4fRYf7TSE6QXQJ+yFeJj6fGh4mHJUPxGtdIgSTIMZzOk6ZhX/C2Ne0gPOcZWMCBaZy//FH4tgGV6jTqKfv9OUKdXgtaQGlbZxNJ/o8fLj5yb0XP8TZlJJtobHcDX2HDPcYlxI8I9QjDwGnr3f7yyXMXoFD/ANOOZcfvTzYO2zF8V1QSfVa3FPC9TE1GlpqPLjvTqZkk7YWLTj2YyKXgrHr4SrmSJP8A+EZDbZNxDCta8n7J2U/7x9V7z6JRrNOJ9TM74VxNTK+V/wCp/LTxIDGgAe33K/h6jkD2aGe5SuO4YfKsccDFOw7Z3ZlxeXMNSSRfNu56XCW4fhA6Jdj1mF6s8P8AfqZfBOINo4/XNzp3DpY9rpn0O1LjdR1PC4moAXNpYqqXc1+Wm15ZrrnPZxkd8/CtdhHqMDrAgE+6Yt/QBKylsqNc2n47I+vFGHKHiqnhZG4PiXiPEwG8h/KGzMVnYn2EzC5ytnF9J2rX1FLgJiHLIgH9W9MxO5BFhoPl2u+ULksQ8l51uZqZrHaRAMqDXhMvEJQSk9m9JaIXEdmqTRrOnwbPgPq8SAXULagwQNOZpLdRGffFo1WO+6DGNg7eVZ3h2kRTGYdOr5y/QGBE29FFcNb/AB1Wy8qp4xxVRpMRdDpGW4HEPgbG8RJa8RMz8pJPlJMaX+u9lJn2hVGvDiQ6DMm0A9BEwGjMEbGfvOqzgcLjOWMzqAAO9DYHfv0a6TgDSTqaOAZ0YLzGqnSTQjR8X/0TjP8Aqcb+5M3hZfZ1iGhwzBJMXnPr6TlrJWlvkqBsM4CQJsJBt3v3Vkf3fVKZPnQrIKTsW1e6rYynz3cCB0vyuPcHJsqR+6kKJjOJ7gn7orK3MDqD+i0KLgDn6Sqj1oQbOJ2n2hDq1c45iJsImbXiJB7LD4ji6jcfUcGsirVZMkNdGZaBElpE3PIJOqnyydXN2z4S4x5qhc/vJA3Vp2vKHl/LYGxBZKlW6Qg5FvNRVYvH4yQ30vIU+bVCFWLbH6q0Y8kSdOp7HzhOwkSdQ3F5qtzHwGHI8pIJbPvFgM/fpOi5zt0TqfaFxCQEt0nSWoTHjrPnUgLhEcJn2lUcTaZ0VhJAp1RqJu8UdoD8rJ2vN51zJsfKRrn9PZSR0lQkkdlTGDJMFHsOquJrEWvOSbS0Z8dOuGnhFUc5aIHe4P4g9nzeafNjsRQcdZ/3gJfEH9J6tUJVKHpODfyQqtxCmAdO5Bsg0xJnRaJy/Ui3LjnJZJfQ+FpwYXK/wBSKL+Rp6z+4kXXdUKnRa9e80nJ5lK15YnJy7/wIQHBTcJvkN80mVgBPv8Amq8Mc7zTUH5KdVgAJ8vZMCKQNuq0sD4X4e6g37iLNz7s38vd3tZAG31Kzm1rZKST3oxIKjMrHJOQ5K/h69Ii6E9w0SGw3aOL/qNl8xaYhzcTEAASwxMZsJlOQ3u8eHcaHFzybj3n0bJO4vlcaGdfF3EKS5r+zXVA+nkzlqNOhmJbKi4C8A1/6Q4a9n+6QHOKxNq4rXKqhJIPJE8xhvQd7TH/AJs7CeYrzLdUhzSHfKqTxNE34RuIB+7RzZdAMhaBBAl3yiOYb/8AJGjsz7jksaJ9P+S6++ZCqYipmLT9JVhI8/6QJ8uhtAC6JjryuPmIy3gnSOz0E3Dkd5xWWJzkiw1PFEDTNRs5gGV7ZbFpMRkWjPPMWt2Ks1mkDz5W9L2Hv7/nN8M8V4n5zIsJG0D0wEfX2XPJx5f+GVSz4K8R7LlYGjUJABdkBfpF3A5nKPU5/VKvwymZJAqOIEt+Zta0EgmCe+V16OXDZ9JFm5+sN1pBLn0ZOF4m6jJpNaDd3Rwa/KcgYyzyWbxzFgUnM5jz/OGNzIe6TbsCNehaW/Y8O/V+Yl4Xl/ZGb0rn+qnEyC73u/7iqfhzj6+GxHJVZUc1zSwtayq8kGx5WU3OGnNkrOJ4VXdyBnOahBJFN2oa7QMOZNa5tEqXhri7KGLqOJe6p8TEU3XVGzTr1C62nRHuFptDZNyXdVJ6x8WOatKzZnUTW9H1aQCCAuJzTJJnGtJlXaTcuqBgfSsZB7I76g11hVlEDTDPaTE6ZH7TfslzXXL4mW+wVqBKzd5A9FP4p9+/wB1nCqRlP1Qa9eZKqINAaDe7QqZi5aOxzOwsI/MLOZVucoo+qz6QAPEECOqO8iBGqqc95JkdTaOqfnmwGnrOtlrCIlU2gZRUL73j6Ry8OV5Rn3jvOaWD/O/3/7VmpP4dMz0Fhf7SaLH9fq01WYXHwD/MfuLz5+61uVHcM9FklzspjvZQpcR9+6Vl+3Qb9Z6BEfUJAv70+n+lhAi0/Y5T0WJKUJTCsHHoEHu0V0FsI4vlWOI4nRaIEXGsX7qN5tFl6yBc4RKSXOkHgjzJ8FSScskg2e2MBCm0I7Mqkf7XdBOWWR3VNlO4J6xqY6y/dKpUEd4OemXvlJ9E3xBtN8y7wEWZxNlH5nOaN7lZi4uUfLELEVJk3vc+xF/XcWufJVqPZLMRkBvvMj+xpjlXXa40rlI6TBOJmZGvbT8w70WcQjMLQY7i+1yJGl4z3m8nqGOsM7dZI7+9zv0iKKfaAcWGKfETPcBvYZhGp1bEZwdLDcfooqQHqIK13k8+X38rpVGztWuF4qjRgtpOee5Db9SbAfZc18QroeEz8FlUEFzHvHs+qTjdgaTYuKjL3POJ9M6q9fRMsm/FrQ8LbNy8z8xNiP6Xb+59Ny6fijgvwMRy3DXNa4CCCW/3Q4B05Q7qBsq3hXG0Xsrv4lWbOKqnEOaBYlz5lzi8kCOXLYRNi7pnG+VdUyEhOy2dhc6mJnSbnaBcxtZU2OzWyN1qF+G/wAgc+IrTyJGcXE9wLBH5rC6sJ7JcwlCeFVcZKYVdh3vKKKTDqx7LMrgr8Y4hTpNLnOHYE2JGcAZnNYOK4vBIa6RyBwLSWEEgtdBylplZtbHlcxdnHu5nAE3Zytb7AAZwpYU5cj+JQHMjLl01RKjlY0HTLRdOI8U1z4y2p7Z/iNVyNFGY/h5a5tQBoBa8OZ2IIPkQfZQqU3NghM0+IYfeMOotNSi0uZzFjHPZqZAIpF38fVYTCGzE4LDNHIGhrsRXjWrU5yP+5yFQgaA5HtdgZrWJ3Ev8TU5FT4m8Gm1jB21Ox7DbNClj8XpLJMKyywO5sUvFdNrMJgxVeCycQxtR7XCwbXqPqAuJJuahJnNxucDhFZ+H+GH1PiUK3wH8gy59wgHQGDpsJG+i7/fL6nnkkgIJHVvYR/wpuc3W/rOmu+eysU6ys0qXNJENOtsl1vaBBaGgqNzl9t76e9uNJrQpOpG+5vNsxaLi8E/Qc9FXM4U5rN7d4LqLrjeLAGFboU5Fh/m4eoHvoL9Cl+B0rslOPLrXJ9kcAb0+g6Xwi3VZ5hCphWWdnB0ew7KDAb+lkz6nQqkKlhOWqHbmwZbX63yTUdJ5s8rL7gMtT6w7BSJWyRZyAAJCfQ3HPm2Y3t5jssys95Igfn/hKmcjr9/wDfmZbOGTdJ3F9HFE6AqUfyIKdZPnL4BNzZKwRyhOGdylf8fQHJBedwT/ALXyG7l56cJvuD50lPfR1RwW44K2wJObhM5DyXkdMhvNSLsusZA3Bv8gSbq7S+2TjJMEyb2z9z+6mJn0+myyPDwJaYEGGPyOWoN1GbkjP9T9K5hFCaYMNjhJ+u4lxO3LcMGbNn69LylsP+nZaQ1DSTqE7/wALMO4thXFxpvAqtNwHSSbxAyBv6G2q6/8Atb+SP6Q6x9LLQKrKrsJIE9VCpXa2zAXE+pu11mHfMlVTKWNlYMSFCJ5jbpAGhFvZJM9GaI8xEZyMrD37JyFOm7ygZS6Y3zGqTauQjOdOmoOqNpUDGoBaKJJJLCe6aolL5sIkGFxOk7/lCeqMxHNf+P2WrhKNqtNvyksex0DJBY4/QnJ3YCNNqcxLbm0jdVb6GjSfVqASeqfN3KNYMjr7SuFCKOiJGZUrJj+C8TxGJaXs5qnK7nEFtN1JrJPwntYGtPIxz31w52XyOFKQZmhO6fhHk9J/NbWCw45GjbOd7+93fqshuhNsUE3TnklkpJeH6F4jxSoGlsQACAXG5a0SRTHy/hv6A9fO3/5Q7PTv6M39Hs2TqKoJo9xHv99V7R8mPPSRxVzaKqPKN7AqE6JlAlOUySRJklISXB0/yWKTPsIqMdI3Gv36YqJuFdhHFmWjVQe3cAW65g7p2UHGm2WEcT5sHTgwwZNqBBxGLa+m6RvdHxRLGgElwOWRtYAQLfzrq5cBPo5OQHzYwqzqRJBDbkcgGgEyMrftPUNqvcGHytuGTJbNwEPfr9evrSJjVa5aWbCMGIbgSQ5Wz0qjwNMdMk2GrPYYJLuoPy66LT8lK5A8aaZTe+4AIJ2+3fLyUqLJmLcuxhpM28vynWJjKZ2gf3Zq0CQdM/eZ/KVJ1aqXX+YjwV/w8NZdafWZ0UvLy7LHKGNtWacL7+x1fXxOWYE6NaY6yM+TdcQ2PvB6qOIxyJ+kE+yZrWZ7jyy2y6dAF0qfV/8A3h73D/43fYrm9L4+1f+l6Ew5qsS5JIW8Jyjo8/iAc9t+Xkz+bL85hcnOwOcbP8udjV7N4l4i3DVTFQNI5QQGhgNOXU/yOxUXfCa0Ml32J3G7GC+7A9sVR6TxXHcnhM8o8j5nPlJ5QGgCJGgJ01PrnlJc9Fs9L8V8XGFAeQ6RAIGe9jJjXPVSQbiafL6FcIJSAGm5g3B5TIGm8w4n2P6q5MXFiJ9JOc+w9jqbRhw+I/O1QDkn8gXHKzlLflGlvQcCEA/4+2XjKd8TrjZwJ3o3EQInMNJnr0M9e/yrYFVNBDhYAhcf3z9q6dCvB2z5/R8w+J8bUo4ipTFJ3w6xzq5fwU/OSBE1CtPE18OxjnNFNxE02uJhzrECOQfR1uy1H2EzccBjQPqTsqNV3MzPc+Sf5dJMYbm8lf0mGdzcjWEklJNE3BNOyEg5pOy3PNXc66S9J/YsQG8eqCm/Db5Tk9P6rBKkl0WnOOjdxGFLfiaYMU2yfm1L/tEqRhVGNHVhzNkRqZMRnHb82OVSw3CZv9+4Hp9ksNjHU25R9MvqZ5Y/Xjk5pnDfNOO5qubYKJHoAJ6eSJCdZVH01OEiEpXTorRpW9p9YBP2kZqFSorNUQZGqrugf8AaOOB5+0p38OGhPuOh/bMLRYfWPqPaUpAhQdUPmJQKjgqNDKRJGcWz13Nta3vkYY2LlWpFIe0/kQQqLahzN+1/fLtKKGOhKc6jWBXjYn8+vXRBrTryCSFxO0A+2o6jnb0qOCp5ZDYyOhPdQqtlDJAMEKSdBFaUgSlJ9KOOGOqFQ5fSrRlFdxtaSZs39nBLhJQWM2lJNFH7OTF9G0bS6O2IcST/wCe/wBO/TJqJW82waBtE/TT8+2QkUZJIySpJJJABJOUqRIK0Y1zzKXKkkkYm8mCfY9D6JdM9/y+kPdPxEJJJoJFI1OyEWZU6X22GyS0rkJUeCfgzOFf4JJKbZFOpyLqO56lJJFBF4IG5z9gq2F8JJIDHWKPx6SQSSD4GF1qmPHX9xqvOOGJJLPMNOLOYAECJJJUJYo5I8fqHmnJJJOhUZB6h3Lk8Nt9FTfNJJDGVKbGqDzJdJCSSBhIQSSST4w1xI6+n36JdJiHmPdJJMNbV/pRdyD/ACHt1z+3TW8jshh3ViuP8bOi97L6fY9Kq7s9d+3n/wDnZ+X8kkkQgf4P/9k=';
      const platform = 'instagram';
      const voice = 'flirty_playful';

      const result = await pipeline({
        imageUrl,
        platform,
        voice,
        nsfw: true
      });

      expect(result).toHaveProperty('facts');
      expect(result).toHaveProperty('variants');
      expect(result).toHaveProperty('ranked');
      expect(result).toHaveProperty('final');
      
      expect(result.final).toHaveProperty('caption');
      expect(result.final).toHaveProperty('hashtags');
      expect(result.final).toHaveProperty('safety_level');
      expect(result.final.safety_level).toMatch(/^(normal|spicy_safe|needs_review)$/);
    });
  });

  describe('Text-Only Pipeline', () => {
    it('should generate content from text prompt only', async () => {
      const result = await pipelineTextOnly({
        platform: 'reddit',
        voice: 'confident',
        theme: 'lingerie shoot',
        context: 'New photo set',
        nsfw: true
      });

      expect(result).toHaveProperty('variants');
      expect(result).toHaveProperty('ranked');
      expect(result).toHaveProperty('final');
      
      expect(result.final.caption).toBeTruthy();
      expect(Array.isArray(result.final.hashtags)).toBe(true);
      expect(result.final.hashtags.length).toBeGreaterThan(0);
    });
  });

  describe('Rewrite Pipeline', () => {
    it('should improve existing caption content', async () => {
      const existingCaption = 'Basic caption that needs improvement';
      
      const result = await pipelineRewrite({
        platform: 'x',
        voice: 'playful',
        existingCaption,
        nsfw: false
      });

      expect(result).toHaveProperty('variants');
      expect(result).toHaveProperty('ranked');
      expect(result).toHaveProperty('final');
      
      expect(result.final.caption).not.toBe(existingCaption);
      expect(result.final.caption.length).toBeGreaterThan(existingCaption.length);
    });
  });

  describe('Platform-Specific Validation', () => {
    it('should enforce platform-specific content rules', async () => {
      const result = await pipelineTextOnly({
        platform: 'x',
        voice: 'confident',
        theme: 'selfie',
        nsfw: false
      });

      // X (Twitter) has specific limits
      expect(result.final.caption.length).toBeLessThanOrEqual(250);
      expect(result.final.hashtags.length).toBeLessThanOrEqual(3);
    });

    it('should handle Instagram content requirements', async () => {
      const result = await pipelineTextOnly({
        platform: 'instagram',
        voice: 'authentic',
        theme: 'lifestyle',
        nsfw: false
      });

      // Instagram has different hashtag requirements
      expect(result.final.hashtags.length).toBeGreaterThanOrEqual(3);
      expect(result.final.hashtags.length).toBeLessThanOrEqual(8);
      expect(result.final.caption.length).toBeLessThanOrEqual(2200);
    });
  });

  describe('Content Safety Validation', () => {
    it('should properly classify content safety levels', async () => {
      const result = await pipelineTextOnly({
        platform: 'reddit',
        voice: 'confident',
        theme: 'professional photoshoot',
        nsfw: true
      });

      expect(['normal', 'spicy_safe', 'needs_review']).toContain(result.final.safety_level);
    });

    it('should handle non-NSFW content appropriately', async () => {
      const result = await pipelineTextOnly({
        platform: 'instagram',
        voice: 'friendly',
        theme: 'coffee shop visit',
        nsfw: false
      });

      expect(result.final.nsfw).toBe(false);
      expect(result.final.safety_level).toBe('spicy_safe'); // NSFW content expected
    });
  });
});