import { describe, it, expect, beforeEach, vi } from 'vitest';

// Mock all external dependencies for integration testing
vi.mock('../../server/lib/gemini.js', () => ({
  textModel: {
    generateContent: vi.fn().mockResolvedValue({
      response: {
        text: () => JSON.stringify([{
          caption: 'Test caption generated by AI',
          hashtags: ['#test', '#ai'],
          safety_level: 'spicy_safe',
          mood: 'confident',
          style: 'authentic',
          cta: 'Check it out',
          alt: 'Test image description',
          nsfw: false
        }])
      }
    })
  },
  visionModel: {
    generateContent: vi.fn().mockResolvedValue({
      response: {
        text: () => JSON.stringify({
          objects: ['woman', 'lingerie'],
          setting: 'bedroom',
          mood: 'confident'
        })
      }
    })
  }
}));

vi.mock('../../server/storage.js', () => ({
  storage: {
    getUserById: vi.fn().mockResolvedValue({
      id: 1,
      username: 'testuser',
      tier: 'pro',
      subscription_status: 'active'
    }),
    createContentGeneration: vi.fn().mockResolvedValue({
      id: 1,
      userId: 1,
      type: 'image_to_content',
      result: {}
    }),
    updateContentGeneration: vi.fn().mockResolvedValue(true)
  }
}));

import { pipeline } from '../../server/caption/geminiPipeline.js';
import { pipelineTextOnly } from '../../server/caption/textOnlyPipeline.js';
import { pipelineRewrite } from '../../server/caption/rewritePipeline.js';

describe('End-to-End Content Generation Workflow', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('Image-to-Content Pipeline', () => {
    it('should complete full workflow from image to final content', async () => {
      const imageUrl = 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCE';
      const platform = 'instagram';
      const voice = 'flirty_playful';

      const result = await pipeline({
        imageUrl,
        platform,
        voice,
        nsfw: true
      });

      expect(result).toHaveProperty('facts');
      expect(result).toHaveProperty('variants');
      expect(result).toHaveProperty('ranked');
      expect(result).toHaveProperty('final');
      
      expect(result.final).toHaveProperty('caption');
      expect(result.final).toHaveProperty('hashtags');
      expect(result.final).toHaveProperty('safety_level');
      expect(result.final.safety_level).toMatch(/^(normal|spicy_safe|needs_review)$/);
    });
  });

  describe('Text-Only Pipeline', () => {
    it('should generate content from text prompt only', async () => {
      const result = await pipelineTextOnly({
        platform: 'reddit',
        voice: 'confident',
        theme: 'lingerie shoot',
        context: 'New photo set',
        nsfw: true
      });

      expect(result).toHaveProperty('variants');
      expect(result).toHaveProperty('ranked');
      expect(result).toHaveProperty('final');
      
      expect(result.final.caption).toBeTruthy();
      expect(Array.isArray(result.final.hashtags)).toBe(true);
      expect(result.final.hashtags.length).toBeGreaterThan(0);
    });
  });

  describe('Rewrite Pipeline', () => {
    it('should improve existing caption content', async () => {
      const existingCaption = 'Basic caption that needs improvement';
      
      const result = await pipelineRewrite({
        platform: 'x',
        voice: 'playful',
        existingCaption,
        nsfw: false
      });

      expect(result).toHaveProperty('variants');
      expect(result).toHaveProperty('ranked');
      expect(result).toHaveProperty('final');
      
      expect(result.final.caption).not.toBe(existingCaption);
      expect(result.final.caption.length).toBeGreaterThan(existingCaption.length);
    });
  });

  describe('Platform-Specific Validation', () => {
    it('should enforce platform-specific content rules', async () => {
      const result = await pipelineTextOnly({
        platform: 'x',
        voice: 'confident',
        theme: 'selfie',
        nsfw: false
      });

      // X (Twitter) has specific limits
      expect(result.final.caption.length).toBeLessThanOrEqual(250);
      expect(result.final.hashtags.length).toBeLessThanOrEqual(3);
    });

    it('should handle Instagram content requirements', async () => {
      const result = await pipelineTextOnly({
        platform: 'instagram',
        voice: 'authentic',
        theme: 'lifestyle',
        nsfw: false
      });

      // Instagram has different hashtag requirements
      expect(result.final.hashtags.length).toBeGreaterThanOrEqual(3);
      expect(result.final.hashtags.length).toBeLessThanOrEqual(8);
      expect(result.final.caption.length).toBeLessThanOrEqual(2200);
    });
  });

  describe('Content Safety Validation', () => {
    it('should properly classify content safety levels', async () => {
      const result = await pipelineTextOnly({
        platform: 'reddit',
        voice: 'confident',
        theme: 'professional photoshoot',
        nsfw: true
      });

      expect(['normal', 'spicy_safe', 'needs_review']).toContain(result.final.safety_level);
    });

    it('should handle non-NSFW content appropriately', async () => {
      const result = await pipelineTextOnly({
        platform: 'instagram',
        voice: 'friendly',
        theme: 'coffee shop visit',
        nsfw: false
      });

      expect(result.final.nsfw).toBe(false);
      expect(result.final.safety_level).toBe('normal');
    });
  });
});